# Generated by Django 2.1.7 on 2019-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KVM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDB',
            fields=[
                ('IP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50)),
                ('gateway', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=30)),
                ('distribution', models.CharField(max_length=20)),
                ('distribution_version', models.CharField(max_length=20)),
                ('architecture', models.CharField(max_length=20)),
                ('kernel', models.CharField(max_length=30)),
                ('processor', models.CharField(max_length=100)),
                ('processor_cores', models.CharField(max_length=20)),
                ('processor_count', models.CharField(max_length=20)),
            ],
        ),
    ]
